[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "obkrnl"
path = "src/main.rs"

[dependencies]
bitflags = "1.3"
clap = { version = "4.1", features = ["derive"] }
iced-x86 = { version = "1.18", features = ["code_asm"] }
libc = "0.2"
memmap2 = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
termcolor = "1.2.0"
thiserror = "1.0"
unicorn-engine = "2.0"
util = { path = "../util" }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.45", features = ["Win32_Foundation", "Win32_System_Diagnostics_Debug", "Win32_System_Memory", "Win32_System_SystemInformation"] }
