[package]
name = "core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
error = { path = "../error" }
ftp = { path = "../ftp" }
humansize = "2.1.3"
param = { path = "../param" }
pkg = { path = "../pkg" }
thiserror = "1.0"
