[package]
name = "core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
error = { path = "../error" }
humansize = "2.1.3"
obfw = { git = "ssh://git@github.com/obhq/firmware-dumper.git", features = ["read", "std"] }
param = { path = "../param" }
pkg = { path = "../pkg" }
thiserror = "1.0"
