name: PR Build
on:
  pull_request:
    branches:
    - '*'
concurrency: pr-${{ github.ref }}
jobs:
  windows:
    name: Build
    uses: ./.github/workflows/ci-windows.yml
  linux:
    name: Build
    uses: ./.github/workflows/ci-linux.yml
